import pytest
from fastapi.testclient import TestClient
from unittest.mock import patch, MagicMock

@pytest.fixture
def mock_core_services():
    with patch("api.ingest.store") as mock_store, \
         patch("api.ingest.caption_image") as mock_clip, \
         patch("api.ingest.transcribe_audio") as mock_whisper, \
         patch("api.ingest.embed_text") as mock_embedder:
        
        # Setup common mock behaviors
        mock_clip.return_value = "Image caption generated by CLIP"
        mock_whisper.return_value = "Audio transcription test"
        mock_embedder.return_value = [0.2] * 384
        mock_store.insert.return_value = None
        
        yield mock_store, mock_clip, mock_whisper, mock_embedder

def test_ingest_text(mock_core_services):
    from main import app
    client = TestClient(app)
    mock_store, _, _, mock_embedder = mock_core_services
    
    response = client.post(
        "/api/ingest/text",
        data={
            "content": "Medical emergency at sector 7",
            "metadata": '{"type": "report"}',
            "zone": "Sector_1",
            "reporter": "User1",
            "priority_level": "High"
        }
    )
    
    assert response.status_code == 200
    assert response.json()["data_type"] == "TEXT"
    
    # Verify embeddings called
    mock_embedder.assert_called_once_with("Medical emergency at sector 7")
    
    # Verify store called
    mock_store.insert.assert_called_once()
    doc = mock_store.insert.call_args[0][0]
    assert doc.content == "Medical emergency at sector 7"
    assert doc.vector == [0.2] * 384
    assert doc.metadata["zone"] == "Sector_1"

def test_ingest_photo(mock_core_services):
    from main import app
    client = TestClient(app)
    mock_store, mock_clip, _, mock_embedder = mock_core_services
    
    # Create fake image bytes
    fake_image = b"fake_image_data"
    
    response = client.post(
        "/api/ingest/photo",
        files={"file": ("test.jpg", fake_image, "image/jpeg")},
        data={"zone": "Sector_2", "reporter": "Drone1", "priority_level": "Urgent"}
    )
    
    assert response.status_code == 200
    assert response.json()["data_type"] == "PHOTO"
    
    # Verify CLIP and embed called
    mock_clip.assert_called_once()
    mock_embedder.assert_called_once_with("Image caption generated by CLIP")
    
    # Verify store called
    mock_store.insert.assert_called_once()
    doc = mock_store.insert.call_args[0][0]
    assert doc.content == "Image caption generated by CLIP"
    assert doc.vector == [0.2] * 384
    assert doc.metadata["reporter"] == "Drone1"

def test_ingest_audio(mock_core_services):
    from main import app
    client = TestClient(app)
    mock_store, _, mock_whisper, mock_embedder = mock_core_services
    
    # Create fake audio bytes
    fake_audio = b"fake_audio_data"
    
    response = client.post(
        "/api/ingest/audio",
        files={"file": ("test.wav", fake_audio, "audio/wav")},
        data={"zone": "Sector_3", "reporter": "Medic1", "priority_level": "Immediate"}
    )
    
    assert response.status_code == 200
    assert response.json()["data_type"] == "AUDIO"
    assert "Audio transcription test" in response.json()["content_preview"]
    
    # Verify transcription
    mock_whisper.assert_called_once()
    
    # Verify embeddings generated from transcription
    mock_embedder.assert_called_once_with("Audio transcription test")
    
    # Verify store called
    mock_store.insert.assert_called_once()
    doc = mock_store.insert.call_args[0][0]
    assert doc.content == "Audio transcription test"
    assert doc.vector == [0.2] * 384
    assert doc.metadata["reporter"] == "Medic1"
